### ISSUE TITLE
Commands wont run and i get this console error

### ISSUE THREAD

**Issue by 3DWafflee** [ustc-zzzz/VirtualChest#30]
[20:51:33 ERROR] [Sponge]: Could not pass ClickInventoryEvent$Primary$Impl to Plugin{id=virtualchest, name=VirtualChest, version=0.4.0, description=A sponge plugin providing virtual chest GUIs for menus., authors=[ustc_zzzz], source=mods/VirtualChest-0.4.0.jar}
java.lang.UnsupportedOperationException: Not recognized
at com.github.ustc_zzzz.virtualchest.unsafe.SpongeUnimplemented.getSlotOrdinal(SpongeUnimplemented.java:54) ~[SpongeUnimplemented.class:?]
at com.github.ustc_zzzz.virtualchest.inventory.VirtualChestInventory$VirtualChestEventListener.fireClickEvent(VirtualChestInventory.java:213) ~[VirtualChestInventory$VirtualChestEventListener.class:?]
at com.github.ustc_zzzz.virtualchest.inventory.VirtualChestInventory$VirtualChestEventListener.access$700(VirtualChestInventory.java:162) ~[VirtualChestInventory$VirtualChestEventListener.class:?]
at com.github.ustc_zzzz.virtualchest.inventory.VirtualChestInventory.lambda$createInventory$0(VirtualChestInventory.java:92) ~[VirtualChestInventory.class:?]
at org.spongepowered.common.item.inventory.custom.CustomInventoryListener.handle(CustomInventoryListener.java:52) ~[CustomInventoryListener.class:1.10.2-5.2.0-BETA-381]
at org.spongepowered.common.item.inventory.custom.CustomInventoryListener.handle(CustomInventoryListener.java:35) ~[CustomInventoryListener.class:1.10.2-5.2.0-BETA-381]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-5.2.0-BETA-381]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305) ~[SpongeEventManager.class:1.10.2-5.2.0-BETA-381]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320) ~[SpongeEventManager.class:1.10.2-5.2.0-BETA-381]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-5.2.0-BETA-381]
at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$32(PacketFunction.java:688) ~[PacketFunction.class:1.10.2-5.2.0-BETA-381]
at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:322) [PacketPhase.class:1.10.2-5.2.0-BETA-381]
at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:251) [CauseTracker.class:1.10.2-5.2.0-BETA-381]
at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:161) [CauseTracker.class:1.10.2-5.2.0-BETA-381]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:157) [PacketUtil.class:1.10.2-5.2.0-BETA-381]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjb000(SourceFile:539) [fl$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:235) [SpongeImplHooks.class:1.10.2-5.2.0-BETA-381]
at net.minecraft.server.MinecraftServer.redirect$onRun$zhi000(SourceFile:4156) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1499) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:338) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by Krosta8** [comment]
You are using an old version. Try the new version 0.4.1.

**Comment by ustc-zzzz** [comment]
Maybe you are using SpongeVanilla? Please update your SpongeVanilla to the latest version (398 now) and check again if the error still exists.

**Comment by 3DWafflee** [comment]
Will try it out tommorow and will let you know. as well i hve a question . Do you have a discord channel? Forgot to tell u ,we tryied latese version and same issue

**Comment by 3DWafflee** [comment]
Yup fixed when i updated sponge vanilla ty so much for the help^^ Again if you have discord group that i can join tell me
