### ISSUE TITLE
Placeholder API bug when using bigtitle

### ISSUE THREAD

**Issue by Lorrainrm** [ustc-zzzz/VirtualChest#52]
Ello!
Got the latest version (Beta 2)
At SpongeForge 2990
This happens when i try to use a 'bigtitle' with a placeholder (from placeholderapi):

```
ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: net.minecraft.util.ReportedException: Loading entity NBT
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1875)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at com.pixelmonmod.pixelmon.config.PixelmonEntityList.createEntityFromNBT(PixelmonEntityList.java:186)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at com.pixelmonmod.pixelmon.storage.PlayerStorage.sendOut(PlayerStorage.java:513)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at com.pixelmonmod.pixelmon.storage.PlayerStorage.sendOut(PlayerStorage.java:494)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at com.github.happyzleaf.pixelmonplaceholders.utility.ParserUtility.parsePokemonInfo(ParserUtility.java:345)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at com.github.happyzleaf.pixelmonplaceholders.Placeholders.trainer(Placeholders.java:62)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at me.rojo8399.placeholderapi.placeholder.trainerPlaceholder_Placeholders_trainer19.parse(Unknown Source)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at me.rojo8399.placeholderapi.placeholder.trainerPlaceholder_Placeholders_trainer19.parse(Unknown Source)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at me.rojo8399.placeholderapi.impl.placeholder.ExpansionBuilderImpl$1.parse(ExpansionBuilderImpl.java:253)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at me.rojo8399.placeholderapi.impl.placeholder.Store.parse(Store.java:324)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at me.rojo8399.placeholderapi.impl.placeholder.Store.parse(Store.java:335)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl.rpt(PlaceholderServiceImpl.java:277)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl.fillPlaceholders(PlaceholderServiceImpl.java:93)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at com.github.ustc_zzzz.virtualchest.unsafe.PlaceholderAPIUtils.fillPlaceholders(PlaceholderAPIUtils.java:53)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at com.github.ustc_zzzz.virtualchest.placeholder.VirtualChestPlaceholderManager.parseText(VirtualChestPlaceholderManager.java:75)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at com.github.ustc_zzzz.virtualchest.action.VirtualChestActions.submitCommands(VirtualChestActions.java:122)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at com.github.ustc_zzzz.virtualchest.action.VirtualChestActionDispatcher.getAction(VirtualChestActionDispatcher.java:153)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at com.github.ustc_zzzz.virtualchest.action.VirtualChestActionDispatcher.runCommand(VirtualChestActionDispatcher.java:98)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at com.github.ustc_zzzz.virtualchest.inventory.VirtualChestInventory$VirtualChestEventListener.lambda$wrapFuture$3(VirtualChestInventory.java:333)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl:rpt:293]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.IllegalStateException: CauseStackManager called from off main thread (current='InnocuousForkJoinWorkerThread{class=class java.util.concurrent.ForkJoinWorkerThread$InnocuousForkJoinWorkerThread, name=ForkJoinPool.commonPool-worker-2, priority=5, group=java.lang.ThreadGroup[name=InnocuousForkJoinWorkerThreadGroup,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:71)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.common.event.SpongeCauseStackManager.getCurrentCause(SpongeCauseStackManager.java:85)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.network.datasync.EntityDataManager.func_187227_b(SourceFile:1095)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.entity.Entity.func_70052_a(Entity.java:2336)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.entity.Entity.func_184195_f(Entity.java:2281)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1845)
22.04 21:36:52 [Server] ForkJoinPool.commonPool-worker-2/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 25 more
```

**Comment by ustc-zzzz** [comment]
Fixed in 866198bd59106770496c10ebe9757fc1008641c1.
